export default {
  tasks: {
    "task-1": {
      id: "task-1",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jacob Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-2": {
      id: "task-2",
      content: "Take out grabaget",
      date: "June 12",
      name: "James Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-3": {
      id: "task-3",
      content: "Take out grabaget",
      date: "June 12",
      name: "July Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-4": {
      id: "task-4",
      content: "Take out grabaget",
      date: "June 12",
      name: "John Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-5": {
      id: "task-5",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jacob Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-6": {
      id: "task-6",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-7": {
      id: "task-7",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-8": {
      id: "task-8",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-9": {
      id: "task-9",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-10": {
      id: "task-10",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-11": {
      id: "task-11",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-12": {
      id: "task-12",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-13": {
      id: "task-13",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-14": {
      id: "task-14",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-15": {
      id: "task-15",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jone",
      equipmentNumber: 123,
      status: "inspection needed",
      color: "#7B1FA2",
    },
  },
  columns: {
    "column-1": {
      id: "column-1",
      title: "Inspection needed",
      taskIds: ["task-1", "task-2", "task-3", "task-5"],
      color: "blue",
    },
    "column-2": {
      id: "column-2",
      title: "Assigned",
      taskIds: ["task-4", "task-6"],
      color: "purple",
    },
    Inspection: {
      id: "Inspection",
      title: "Inspection",
      taskIds: ["task-7", "task-8", "task-9"],
      color: "teal",
    },
    Inspected: {
      id: "Inspected",
      title: "Inspected",
      taskIds: [
        "task-10",
        "task-11",
        "task-12",
        "task-13",
        "task-14",
        "task-15",
      ],
      color: "orange",
    },
  },

  columnOrder: ["column-1", "column-2", "Inspection", "Inspected"],
};
