export default {
  tasks: {
    "task-1": {
      id: "task-1",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jacob Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-2": {
      id: "task-2",
      content: "Take out grabaget",
      date: "June 12",
      name: "James Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-3": {
      id: "task-3",
      content: "Take out grabaget",
      date: "June 12",
      name: "July Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-4": {
      id: "task-4",
      content: "Take out grabaget",
      date: "June 12",
      name: "John Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-5": {
      id: "task-5",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jacob Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#f15f41",
    },
    "task-6": {
      id: "task-6",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-7": {
      id: "task-7",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-8": {
      id: "task-8",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-9": {
      id: "task-9",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-10": {
      id: "task-10",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-11": {
      id: "task-11",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-12": {
      id: "task-12",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-13": {
      id: "task-13",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-14": {
      id: "task-14",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
    "task-15": {
      id: "task-15",
      content: "Take out grabaget",
      date: "June 12",
      name: "Jeniffer Jones",
      price: 233,
      description: "Tire replacement",
      status: "inspection needed",
      color: "#7B1FA2",
    },
  },
  columns: {
    ServiceNeeded: {
      id: "ServiceNeeded",
      title: "Service Needed",
      taskIds: ["task-1", "task-2", "task-3", "task-5"],
      color: "blue",
    },
    Waiting: {
      id: "Waiting",
      title: "Waiting",
      taskIds: ["task-4", "task-6"],
      color: "purple",
    },
    InService: {
      id: "InService",
      title: "In Service",
      taskIds: ["task-7", "task-8", "task-9"],
      color: "teal",
    },
    FullyServiced: {
      id: "FullyServiced",
      title: "Fully Serviced",
      taskIds: [
        "task-10",
        "task-11",
        "task-12",
        "task-13",
        "task-14",
        "task-15",
      ],
      color: "orange",
    },
  },

  columnOrder: ["ServiceNeeded", "Waiting", "InService", "FullyServiced"],
};
